# Generated by Django 6.0.5 on 2026-06-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_imagecontent_textcontent_videocontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
    ]
