# Generated by Django 6.0.5 on 2026-06-17 19:25

import apps.courses.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_options_alter_module_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcontent',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='content_ptr',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контенттер'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Қосылған уақыты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(default='', upload_to=apps.courses.models.get_course_file_upload_path, verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Файл өлшемі (байт)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='mime_type',
            field=models.CharField(default=0, editable=False, max_length=100, verbose_name='MIME-түрі'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='original_filename',
            field=models.CharField(default='', editable=False, max_length=255, verbose_name='Түпнұсқа файл атауы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Реттік нөмірі'),
        ),
        migrations.DeleteModel(
            name='ImageContent',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
    ]
