# Generated by Django 6.0.5 on 2026-07-01 12:29

import apps.courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0004_remove_textcontent_content_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.content')),
                ('content', models.TextField()),
                ('h_level', models.SmallIntegerField(choices=[(1, '1-деңгейлі'), (2, '2-деңгейлі'), (3, '3-деңгейлі'), (4, '4-деңгейлі'), (5, '5-деңгейлі'), (6, '6-деңгейлі')], default=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.content',),
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.content')),
                ('content_url', models.FileField(upload_to=apps.courses.models.get_course_file_upload_path, verbose_name='Сурет')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.content',),
        ),
        migrations.CreateModel(
            name='PresentationContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.content')),
                ('content_url', models.FileField(upload_to=apps.courses.models.get_course_file_upload_path, verbose_name='Презентация')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.content',),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.content')),
                ('content', models.TextField()),
                ('text_type', models.TextField(choices=[('important', 'Маңызды ақпарат'), ('danger', 'Сақтық ақпарат'), ('tip', 'Кеңес'), ('base', 'Қарапайым мәтін')], default='base')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.content',),
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.content')),
                ('content_url', models.FileField(upload_to=apps.courses.models.get_course_file_upload_path, verbose_name='Бейне')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.content',),
        ),
        migrations.CreateModel(
            name='YoutubeVideoContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.content')),
                ('content_url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.content',),
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='content_kz',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='content',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='content',
            name='file',
        ),
        migrations.RemoveField(
            model_name='content',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='content',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='content',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
