# Generated by Django 6.0.5 on 2026-06-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithoutQuizContext',
            fields=[
                ('quizcontext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzes.quizcontext')),
            ],
            options={
                'abstract': False,
            },
            bases=('quizzes.quizcontext',),
        ),
        migrations.RemoveField(
            model_name='quizcontext',
            name='title',
        ),
        migrations.RemoveField(
            model_name='quizcontext',
            name='dataset_file',
        ),
        migrations.RemoveField(
            model_name='quizcontext',
            name='text',
        ),
        migrations.AddField(
            model_name='quizcontext',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='WithQuizContext',
            fields=[
                ('quizcontext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzes.quizcontext')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to='derek')),
            ],
            options={
                'abstract': False,
            },
            bases=('quizzes.quizcontext',),
        ),
    ]
