# Generated by Django 6.0.5 on 2026-06-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirnesheJauaptyqSuraq',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzes.question')),
            ],
            options={
                'abstract': False,
            },
            bases=('quizzes.question',),
        ),
    ]
